### ISSUE TITLE
fails to build with fontmake?

### ISSUE THREAD

**Issue by alexmyczko** [DunwichType/Margherita#1]
```
$ fontmake -g Margherita.glyphs -i -o otf 
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "Margherita.glyphs" file into <GSFont>
Traceback (most recent call last):
  File "/usr/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==2.0.10', 'console_scripts', 'fontmake')()
  File "/usr/lib/python3/dist-packages/fontmake/__main__.py", line 425, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 663, in run_from_glyphs
    designspace_path = self.build_master_ufos(
  File "/usr/lib/python3/dist-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 142, in build_master_ufos
    font = glyphsLib.GSFont(glyphs_path)
  File "/usr/lib/python3/dist-packages/glyphsLib/classes.py", line 3561, in __init__
    p.parse_into_object(self, fp.read())
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 63, in parse_into_object
    i = self._parse_dict_into_object(res, text, 1)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 103, in _parse
    return self._parse_list(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 193, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 97, in _parse
    return self._parse_dict(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 150, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 166, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 125, in _parse
    value = self.current_type(value)
  File "/usr/lib/python3/dist-packages/glyphsLib/types.py", line 129, in __init__
    self.value = self.fromString(value)
  File "/usr/lib/python3/dist-packages/glyphsLib/types.py", line 96, in fromString
    return [parse_float_or_int(i) for i in self.regex.match(src).groups()]
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by DunwichType** [comment]
Unfortunately I am not qualified to diagnose Fontmake failures. This probably needs to be taken up with the Fontmake developers.
